apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: APP_NAME
  description: The name for the application
  displayName: Application Name
  required: true
  value: previous-wealth
- name: WELCOME_IMAGE_NAME
  description: The Welcome App's image name
  displayName: Image Name
  required: true
  value: fabric8/launcher-creator-welcome-app
- name: WELCOME_IMAGE_TAG
  description: The Welcome App's image tag
  displayName: Image Tag
  required: true
  value: latest
- name: WELCOME_APP_CONFIG
  description: The configuration for the welcome app
  displayName: Welcome App Configuration
  required: true
  value: |-
    {
      "parts": [{
        "capabilities": [{
          "module": "capability-health",
          "props": {},
          "extra": {
            "category": "backend"
          }
        }, {
          "module": "capability-rest",
          "props": {},
          "extra": {
            "category": "backend",
            "sourceMapping": {
              "greetingEndpoint": "src/main/java/io/openshift/booster/http/GreetingEndpoint.java"
            }
          }
        }, {
          "module": "capability-database",
          "props": {
            "databaseType": "mysql"
          },
          "extra": {
            "category": "backend",
            "databaseInfo": {
              "image": "mysql",
              "service": "previous-wealth-database-bind"
            },
            "sourceMapping": {
              "dbEndpoint": "src/main/java/io/openshift/booster/database/FruitResource.java"
            }
          }
        }, {
          "module": "capability-welcome",
          "props": {},
          "extra": {
            "category": "support"
          }
        }],
        "shared": {
          "runtime": {
            "name": "quarkus",
            "version": "community"
          },
          "maven": {
            "groupId": "org.openshift.appgen",
            "artifactId": "my-app",
            "version": "1.0.0"
          }
        },
        "extra": {
          "runtimeInfo": {
            "enumInfo": {
              "id": "quarkus",
              "name": "Quarkus",
              "description": "A Kubernetes Native Java stack tailored for GraalVM and OpenJDK HotSpot, crafted from the best of breed Java libraries and standards",
              "icon": "data:image/svg+xml,%3Csvg id='Layer_1' data-name='Layer 1' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1280 775'%3E%3Cdefs%3E%3Cstyle%3E.cls-1%7Bfill:%23091313;%7D.cls-2%7Bfill:%234695eb;%7D.cls-3%7Bfill:%23ff004a;%7D%3C/style%3E%3C/defs%3E%3Ctitle%3Equarkus_logo_vertical_rgb_1280px_default%3C/title%3E%3Cpath class='cls-1' d='M160.58,641.56q0,33.13-13.41,55.06a66.75,66.75,0,0,1-37.84,29.7L150.61,769h-29.3L87.49,730.1l-6.52.23q-38.32,0-59.15-23.28T1,641.33q0-42.09,20.88-65.25T81.2,552.91q37.38,0,58.38,23.58T160.58,641.56Zm-138.22,0q0,35,15,53.11T81,712.77q28.83,0,43.54-18t14.71-53.17q0-34.77-14.65-52.75t-43.37-18q-28.81,0-43.83,18.09T22.36,641.56Z'/%3E%3Cpath class='cls-1' d='M359.4,555.62V667.14q0,29.48-17.91,46.33t-49.24,16.86q-31.32,0-48.47-17t-17.14-46.69v-111h20.17V668.09q0,21.57,11.86,33.12t34.88,11.56q22,0,33.82-11.62t11.87-33.3V555.62Z'/%3E%3Cpath class='cls-1' d='M543.51,728l-21.59-54.81H452.39L431,728h-20.4L479.2,554.91h17L564.39,728Zm-27.88-72.85-20.17-53.4q-3.91-10.14-8.07-24.88a222.66,222.66,0,0,1-7.47,24.88l-20.41,53.4Z'/%3E%3Cpath class='cls-1' d='M637.57,656.3V728H617.4V555.62H665q31.9,0,47.16,12.14t15.25,36.55q0,34.19-34.89,46.21L739.61,728H715.76l-42-71.67Zm0-17.21h27.64q21.36,0,31.33-8.43t10-25.29q0-17.08-10.14-24.64t-32.57-7.54H637.57Z'/%3E%3Cpath class='cls-1' d='M922.05,728H898.32l-63.23-83.58-18.15,16V728H796.76V555.62h20.18v85.47l78.66-85.47h23.85l-69.77,74.86Z'/%3E%3Cpath class='cls-1' d='M1106,555.62V667.14q0,29.48-17.91,46.33t-49.24,16.86q-31.32,0-48.47-17t-17.14-46.69v-111h20.17V668.09q0,21.57,11.86,33.12t34.88,11.56q22,0,33.82-11.62t11.86-33.3V555.62Z'/%3E%3Cpath class='cls-1' d='M1279,682.12q0,22.75-16.61,35.48t-45.09,12.73q-30.84,0-47.45-7.9V703.1a124.44,124.44,0,0,0,23.25,7.07,123,123,0,0,0,24.92,2.6q20.16,0,30.37-7.61t10.2-21.16q0-9-3.61-14.68t-12.11-10.55q-8.49-4.83-25.8-11-24.21-8.61-34.59-20.39t-10.38-30.77q0-19.92,15.07-31.72T1227,553.15q25.88,0,47.58,9.43L1268.32,580q-21.48-9-41.76-9-16,0-25,6.84t-9,19q0,9,3.32,14.68T1207,622.05q7.89,4.77,24.15,10.55,27.29,9.67,37.55,20.75T1279,682.12Z'/%3E%3Cpolygon class='cls-2' points='703.75 73.78 639.99 110.59 703.75 147.4 703.75 73.78'/%3E%3Cpolygon class='cls-3' points='576.22 73.78 576.22 147.4 639.99 110.59 576.22 73.78'/%3E%3Cpolygon class='cls-1' points='703.75 147.4 639.99 110.59 576.22 147.4 639.99 184.22 703.75 147.4'/%3E%3Cpolygon class='cls-2' points='508.99 190.23 572.75 227.04 572.75 153.41 508.99 190.23'/%3E%3Cpolygon class='cls-3' points='572.75 300.67 636.51 263.86 572.75 227.04 572.75 300.67'/%3E%3Cpolygon class='cls-1' points='572.75 153.41 572.75 227.04 636.51 263.86 636.51 190.23 572.75 153.41'/%3E%3Cpolygon class='cls-2' points='707.22 300.67 707.22 227.04 643.46 263.86 707.22 300.67'/%3E%3Cpolygon class='cls-3' points='770.98 190.23 707.22 153.41 707.22 227.04 770.98 190.23'/%3E%3Cpolygon class='cls-1' points='643.46 263.86 707.22 227.04 707.22 153.41 643.46 190.23 643.46 263.86'/%3E%3Cpath class='cls-2' d='M778.37,1H501.6a68.91,68.91,0,0,0-68.71,68.7V346.48a68.91,68.91,0,0,0,68.71,68.7H691.14L640,290.92l-37.12,78.46H501.6a23.21,23.21,0,0,1-22.9-22.9V69.7a23.21,23.21,0,0,1,22.9-22.9H778.37a23.21,23.21,0,0,1,22.9,22.9V346.48a23.21,23.21,0,0,1-22.9,22.9H718.31l18.86,45.8h41.2a68.91,68.91,0,0,0,68.71-68.7V69.7A68.91,68.91,0,0,0,778.37,1Z'/%3E%3C/svg%3E",
              "metadata": {
                "categories": ["backend"],
                "language": "java",
                "website": "https://quarkus.io/"
              }
            },
            "image": "fabric8/s2i-java",
            "service": "previous-wealth",
            "route": "previous-wealth"
          },
          "category": "backend"
        }
      }],
      "application": "previous-wealth"
    }
- name: FRONTEND_SERVICE_NAME
  description: The frontend service name for the welcome app
  displayName: Frontend service name
  required: true
  value: previous-wealth
- name: BACKEND_SERVICE_NAME
  description: The backend service name for the welcome app
  displayName: Backend service name
  required: true
  value: previous-wealth
- name: SOURCE_REPOSITORY_PROVIDER
  description: The source repository provider
  displayName: Source Provider
  value: GitHub
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
- name: OPENSHIFT_CONSOLE_URL
  description: The OpenShift Console URL for the application
  displayName: OpenShift Console URL
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: ${WELCOME_IMAGE_TAG}
      from:
        kind: DockerImage
        name: ${WELCOME_IMAGE_NAME}:${WELCOME_IMAGE_TAG}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}-welcome
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}-welcome
      spec:
        containers:
        - image: ${WELCOME_IMAGE_NAME}:${WELCOME_IMAGE_TAG}
          name: ${APP_NAME}-welcome
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 8M
            limits:
              cpu: 50m
              memory: 100Mi
          env:
          - name: WELCOME_APP_CONFIG
            value: ${WELCOME_APP_CONFIG}
          - name: OPENSHIFT_CONSOLE_URL
            value: ${OPENSHIFT_CONSOLE_URL}
          - name: SOURCE_REPOSITORY_PROVIDER
            value: ${SOURCE_REPOSITORY_PROVIDER}
          - name: SOURCE_REPOSITORY_URL
            value: ${SOURCE_REPOSITORY_URL}
          - name: FRONTEND_SERVICE_NAME
            value: ${FRONTEND_SERVICE_NAME}
          - name: BACKEND_SERVICE_NAME
            value: ${BACKEND_SERVICE_NAME}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}-welcome
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}-welcome:${WELCOME_IMAGE_TAG}
      type: ImageChange
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}-welcome
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
    annotations:
      console.alpha.openshift.io/overview-app-route: 'true'
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APP_NAME}-welcome
